# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_store_complex_v_invc <- function(d) {
    .Call('_qshapr_r_store_complex_v_invc', PACKAGE = 'qshapr', d)
}

r_store_complex_root <- function(d) {
    .Call('_qshapr_r_store_complex_root', PACKAGE = 'qshapr', d)
}

r_complex_dot_v2 <- function(p, v_invc, d) {
    .Call('_qshapr_r_complex_dot_v2', PACKAGE = 'qshapr', p, v_invc, d)
}

create_tree_explainer_cpp <- function(tree_model) {
    .Call('_qshapr_create_tree_explainer_cpp', PACKAGE = 'qshapr', tree_model)
}

get_tree_summary <- function(explainer_ptr) {
    .Call('_qshapr_get_tree_summary', PACKAGE = 'qshapr', explainer_ptr)
}

rsq <- function(explainer_ptr, x, y, T0_x) {
    .Call('_qshapr_rsq', PACKAGE = 'qshapr', explainer_ptr, x, y, T0_x)
}

