# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_inv_binom_coef <- function(d) {
    .Call('_qshapr_r_inv_binom_coef', PACKAGE = 'qshapr', d)
}

r_complex_v_invc_degree <- function(d) {
    .Call('_qshapr_r_complex_v_invc_degree', PACKAGE = 'qshapr', d)
}

